[package]
name = "shuttle"
version = "0.2.0"
edition.workspace = true

[dependencies]
anyhow = "1"
dotenvy = "0.15.7"
pavex = "0.1.78"
server = { path = "../server" }
server_sdk = { path = "../server_sdk" }
shuttle-runtime = { version = "0.52.0", default-features = false }
tracing = "0.1.41"
